KANBAN_PATH: /Users/zhaoxuefeng/GitHub/obsidian/工作/事件看板/事件看板.md
WORK_CANVAS_PATH:
- /工程系统级设计/能力级别/grapher/grapher.canvas
- /工程系统级设计/能力级别/kanban/kanban.canvas
- /工程系统级设计/能力级别/llmada/llmada.canvas
- /工程系统级设计/能力级别/obragtools/obragtools.canvas
- /工程系统级设计/能力级别/promptlibz/promptlibz.canvas
- /工程系统级设计/能力级别/pypidoctor/pypidoctor.canvas
- /工程系统级设计/能力级别/reallife/reallife.canvas
- /工程系统级设计/能力级别/toolsz/toolsz.canvas
- /工程系统级设计/能力级别/szrsfeelthefield/szrsfeelthefield.canvas
- /工程系统级设计/能力级别/szrsmemory/szrsmemory.canvas
- /工程系统级设计/项目级别/数字人生/模拟资质认证/模拟资质认证.canvas
- /工程系统级设计/项目级别/数字人生/DigitalLife/DigitalLife.canvas
- /工程系统级设计/项目级别/自动化工作/coder/coder.canvas
